{% set version = "3.3.7" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/{{ version }}.tar.gz
  sha1: 743c1dc00c6680229d8cc87d44debe5a71d15c01

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [ppc64le]

test:
  requires:
    - {{ compiler('cxx') }}
  files:
    - test.cc
  commands:
    - test -d $PREFIX/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\Eigen exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  license_family: Other
  summary: C++ template library for linear algebra
