{% set version = "5.0.1" %}
{% set name = "eigen" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/lib{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9c326dc8c05cd1e044c71f30f1b2e34a6161a3b6ecf445d56b53ff1669e3dec

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >3.10
    - ninja-base

test:
  commands:
    - test -f $PREFIX/share/pkgconfig/eigen3.pc  # [unix]
    - test -f $PREFIX/share/eigen3/cmake/Eigen3Config.cmake  # [unix]
    - test -f $PREFIX/include/eigen3/Eigen/Core  # [unix]
    - if not exist %PREFIX%\\Library\\share\\eigen3\\cmake\\Eigen3Config.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\eigen3.pc exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\eigen3\\core exit 1  # [win]

about:
  home: https://eigen.tuxfamily.org
  license: MPL-2.0
  license_family: Other
  license_file: COPYING.MPL2
  summary: "Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."
  description: "Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."
  dev_url: https://gitlab.com/libeigen/eigen
  doc_url: https://libeigen.gitlab.io
