{% set version = "3.3.7" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha256: d56fbad95abf993f8af608484729e3d87ef611dd85b3380a8bad1d5cbc373a57

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [ppc64le or aarch64]

test:
  requires:
    - {{ compiler('cxx') }}
  files:
    - test.cc
  commands:
    - test -d $PREFIX/include/eigen3  # [unix]
    - if not exist %PREFIX%\\Library\\include\\Eigen exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  license_family: Other
  summary: C++ template library for linear algebra
