{% set version = "3.4.0" %}

package:
  name: eigen
  version: {{ version }}

source:
  fn: eigen-{{ version }}.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha1: d222db69a9e87d9006608e029d1039039f360b52

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
  files:
    - test.cc
  commands:
    - test -d $PREFIX/include/eigen3  # [unix]
    - if not exist %CONDA_PREFIX%\\Library\\include\\Eigen exit 1  # [win]

about:
  home: http://eigen.tuxfamily.org/
  dev_url: https://gitlab.com/libeigen/eigen
  doc_url: https://eigen.tuxfamily.org/dox/
  license: MPL2
  license_family: Other
  summary: C++ template library for linear algebra
  description: |
    Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
