travis:
  secure:
    BINSTAR_TOKEN: nH6rfyMd8cSTZO8QH1wQc/fgeN5vA25uv4N0z0wfe3vMb/s7GpghZfUtsffefe/qvh8inwg7BStsPggL8EJ0ahAK0uaMVRYHNJOj2Gw2J3Spg/7Cb5S/Zs82ec5oL0wW1fW75Dmb5wj4PlCgJEGdLPy9T/KiYNeW/6JzyXFSQnGgDwvt1c8jPQOmNM0ZP1AtU1H/d37INjOhHvTQrvPzjkHg3warKfEJClSUjhDdxLVuY1RvqsPlIkwqg50jZrDbX5ePqQXTxzi5sDdnNV8kXK+LTGQntapvJ1jWyPIHLib78vZZ+UG8K8jZYlzHdb1MRhmqs3loKuFtx8occLunHD7BIN9xEx0jLTfhN134+NuDzpEwRb6a6WR1P7xSMOtUOaNHqRuEmaxvwc1OraQhllPYG1NdmFUldvYVV0aMl0Ehytx6pqnM8E1NnFWfhBRPoBfSp6m4N0oTQ0A+fs1TtoAbkRI4/EU5kZp21Oh8/6jP7N3hFmP2l/VV6QpQKvNzrIBZtVlXbi1479/csRLE1pbt4xm9dI87lDNpf71rmdGZMPpq0v/QlQTCv75PC48M2Kl8EuEs9SgjdWVP7KLmKsAOC9KdT+9JtiQaJVcpcEY5NVEXTDlpqC+zALEDvzPR1MJ/JTBqo577CShKSwuAcEBz7Fg3J5ji0KQ92MhQTy4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
