travis:
  secure:
    BINSTAR_TOKEN: CMSDwscPeavUh4dMiIVpgCn4WGIx1o7qlYnEqGOHI5UmNUJTizqdvgnAcH4wxxqz5q3jnNgixjpR5oNoxgnczWG7jTPWPTl96srDRZEfdgIPqd7dC0l/Yx3ZLcroiAsenJ+UXzAquwmGL869GdOsGQ3R3LMibnqdFB9fyP3CxbF9vR+SNLDEhwcyRviIXcjBpjcwtfjJjOL+Wv/5KBpqJdBYJiTp8Lp5e1Men8u1kbbcq64501++vrhFXMFkZOfbWjsI8bYNzknaraQrxnglvv1ICJi03XVArPBY+Dp2FGryTyxd87PDJjLJ1Opv2SgZUV/5ZFaag+qoJIaGp6/0hyvM6/IrFRMldy7QdbXwZGOViuBd3ua9Nav77VUwnwf5oPUpELmudbZTLzw70VZTJT8ecyxCWREFEyEoxHG4AtduSv9K6EbQSdKkfgbjzJG1mKdMceUfTEDFvLkgLZTCqrL9A014bAntz7Le5WFivAqOiqTcYaHQ32hkVKqkQbYxCRenLSgkzA/NBuEauDlk7FYAEgF83W6295eCio9OoX/o5FEjwcIkEpKnkVA1D4RpvWf/hn1FS0jsYdsPoKVYnP3pYufmlMiQZ9uWk6DRC1LCceMKs8cWpbpx9LgKc8stfQgWEECyOhtfL0dLNAYeMkr428PEJldxPMPGqtoLBhY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
